# Python Frameworks for Machine Learning

In this tutorial, you will learn how to operate with two of the most fundamental frameworks when it comes to Machine Learning: Pandas and NumPy

## NumPy (https://github.com/numpy/numpy)

NumPy is a Python library aimed at array operations. This library is well-suited for Machine Learning tasks, where speed and resources are very important (processing using NumPy arrays is up to 50x faster than doing so using Python lists).

Let's begin by installing and importing the library. (You just have to run the next cells)

In [ ]:
pip install numpy

Note: Usually, you need to create a Python environment and install all the required packages there. However, since this is a jupyter notebook tutorial, we can do it like this.

In [7]:
import numpy as np

Now, let's do some exercises leveraging the potentialities of NumPy

#### Exercise 1 - Create a numpy array

It is quite simple to create a numpy array. You'll see an example and reproduce the method, using a different sequence of numbers.

In [ ]:
example_array = np.array([1, 2, 3, 4, 5])
print("Here's an example: " + str(example_array) + "\n")
print("Now it's your turn.\n")

your_array = #insert code here

print(your_array)

As you can see, we used a list to create a NumPy array, but we can also use tuples.

In [15]:
array_from_tuple = np.array((1, 2, 3, 4, 5))

print(array_from_tuple)

[1 2 3 4 5]


#### Exercise 2 - Multi-dimensional arrays

So far, we've introduced one-dimensional arrays (which are basically matrices), but NumPy offers the possibility to create arrays with n dimensions. See an example:

In [17]:
array_3d = np.array([[2, 3, 4], [5, 6, 7], [2, 3, 7]])

print(array_3d)

[[2 3 4]
 [5 6 7]
 [2 3 7]]


Now, create an array with 7 dimensions.

In [ ]:
array_7d = #insert code here

print(array_7d)

You can check the shape of your array using the following method:

In [ ]:
print(array_7d.shape())

#### Exercise 4 - Indexation

In NumPy, you access an element within an array using straight brackets - [] - same as you do with Python lists. See the following example.

In [19]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(array[0])
print(array[1])
print(array[7])


1
2
8


Insert the code necessary to access and print the 9th element of the previous array.

In [ ]:
ninth = #insert code here

print(ninth)

What is the length of the array? Inser the code needed to answer this question.

In [22]:
arr_len = #insert code here

print()

9


Since the length of the array is 9, the 9th element of the array is the last one. You can access the last element of an array in a different manner:

In [24]:
last_element = array[-1]

print(last_element)

9


For multi-dimensional arrays, you need to use multiple indexes. Consider the following bi-dimensional array.

In [25]:
bidim_array = np.array([[1, 2, 3], [4, 5, 6]])

print(bidim_array)

[[1 2 3]
 [4 5 6]]


You want to access the element with value "4" in this array, which is situate in the second row, first column. How can you do that?

In [27]:
required_element = #insert code here

print(required_element)

4


#### Exercise 5 - Array Slicing

Now that you know all about indexing, let's talk slicing. You can slice sub-parts of arrays using the following notation:

In [29]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_array = array[1:6]

print(sliced_array)

[2 3 4 5 6]


Your turn. Access and print the 3 middle elements of the array ("4", "5", and "6") using a slicing technique.

In [ ]:
slice = #insert code here

print(slice)

You can also use negative indexes. See the example and try it yourself.

In [31]:
print(array[-6:-2])


[4 5 6 7]


In [ ]:

your_slice = #insert code here

print(yout_slice)

Now let's get a sequence of elements through steps.

In [32]:
step_slice = array[1:9:2]

print(step_slice)

[2 4 6 8]


Your move. Try different step and limit combinations (including negatives).

In [ ]:
my_step_slice = #insert code here

print(my_step_slice)

#### Exercise 6 - Data Types

We've only worked with integers so far, but ndarrays are compatible with other types of data. Try to create an array out of a list of strings.

In [ ]:
str_array = #insert code here

print(str_array)

Did it work? Now try a list of floats.

In [ ]:
flt_array = #insert code here

print(flt_array)

You can also convert arrays to a different data type (as long as the conversion is possible). Check the following conversion of an integer array to a boolean.

In [36]:
int_array = np.array([0, 1, 0, 0])

bool_array = int_array.astype('bool')

print(bool_array)

[False  True False False]


Now convert the float array you created into an integer array

In [ ]:
my_int_array = #insert code here

print(my_int_array)

#### Exercise 7 - Join Arrays

In [ ]:
pip install pandas

In [ ]:
import pandas